apiVersion: v1
kind: Service
metadata:
  name: migration-service
spec:
  selector:
    app: migration
  ports:
    - protocol: TCP
      port: 8090 # The port on which the service will be exposed
      targetPort: 8085 # The port on which the pod containers are listening
  type: LoadBalancer # Change this to ClusterIP or NodePort if needed

