apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-deployment
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: migration
  template:
    metadata:
      labels:
        app: migration
    spec:
      imagePullSecrets:
        - name: regcrd
      containers:
        - name: migration
          image: ovaledgellc/internaltest:migration_11_12_23
          env:
            - name: OVALEDGE_MYSQL_URL
              value: {{ .Values.dbdetails.OVALEDGE_MYSQL_URL | quote }}
            - name: OVALEDGE_MYSQL_USER
              value: {{ .Values.dbdetails.OVALEDGE_MYSQL_USER | quote }}
            - name: OVALEDGE_MYSQL_PWORD
              value: {{ .Values.dbdetails.OVALEDGE_MYSQL_PWORD | quote }}
          ports:
            - containerPort: 8085

